In [1]:
import pandas as pd
import numpy as np

from skmultilearn.problem_transform import BinaryRelevance
from sklearn.svm import SVC

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import GenericUnivariateSelect

from sklearn.datasets import make_multilabel_classification
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

from scipy import sparse

from library.MyBinaryRelevanceFeatureSelect import MyBinaryRelevanceFeatureSelect


In [18]:
# class MyBinaryRelevanceFeatureSelect():
   
#     def fit(self, X, y):
        
#         # I'm using a gaussian naive bayes base classifier
#         self.BinaryRelevanceObject = BinaryRelevance(classifier = SVC(gamma= 'auto'), require_dense = [True, True])
        
#         # fitting the data
#         self.BinaryRelevanceObject.fit(X, y)
        
#         #the classifiers for each label
#         self.classifiers = self.BinaryRelevanceObject.classifiers_

#         return self
        
# #     def partition(self):
# #         return self.BinaryRelevanceObject.partition_#BinaryRelevanceObject
    
# #     def model_count(self):
# #         return self.BinaryRelevanceObject.model_count_

#     def predict(self, X, y=None):
#         return self.BinaryRelevanceObject.predict(X)
    
# #     def feature_select(self, X, y):
        
# #         #features_selected = []

# # #         X_new = SelectKBest(chi2, k=2)

# # #         # the feature selecting
# # #         X_new.fit(X, y)

# # #         # save indices of the saved attributes
# # #         selected_attributes_indices = X_new.get_support(indices = True)
        
# #         transformer = GenericUnivariateSelect(chi2, 'k_best', param=2)
# #         X_new = transformer.fit_transform(X, y)
# #         #X_new.shape
# #         selected_attributes_indices = transformer.get_support(indices = True)
        
# #         return selected_attributes_indices
    
#     def feature_select(self, X, y, transformer):
        
#         #transformer = SelectKBest(chi2, k=2)
#         transformer.fit(X, y)
#         selected_attributes_indices = transformer.get_support(indices = True)
        
#         return selected_attributes_indices
    
#     def sets_of_selected_features(self, X, predictions, classifier, transformer ): #X is the df with the predictions
#         selected_features_array = []

#         for i in predictions:
#             indices_features_selected = clf.feature_select(X, predictions[i], transformer)
#             selected_features_array.append(indices_features_selected)
    
#         return selected_features_array

In [2]:
#making the dataset
X, y = make_multilabel_classification(n_classes=6, n_labels=2,sparse = True, allow_unlabeled=False, random_state=1)

#split in training and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

#intializing with the classifier class
clf = MyBinaryRelevanceFeatureSelect()

#fitting the data for training
clf.fit(X_train, y_train)

#sparse matrix
predictions = clf.predict(X_test)

#make a dataframe
x = pd.DataFrame(predictions.toarray())


#the feature selection
#x = clf.feature_select1(X_test,x[0],GenericUnivariateSelect(chi2, 'k_best', param=4))
#SelectKBest(chi2, k=5)
xx = clf.feature_select(X_test,x[0],SelectKBest(chi2, k=3))#[:]#array([ 1,  6, 14, 16, 19], dtype=int64)

In [3]:
clf

In [4]:
clf.sets_of_selected_features(X_test,x,clf,SelectKBest(chi2, k=3))

[array([ 3, 16, 19], dtype=int64),
 array([17, 18, 19], dtype=int64),
 array([17, 18, 19], dtype=int64),
 array([ 2,  3, 19], dtype=int64),
 array([11, 18, 19], dtype=int64),
 array([17, 18, 19], dtype=int64)]

In [5]:
arr = clf.sets_of_selected_features(X_test,x,clf,SelectKBest(chi2, k=3))
arr

[array([ 3, 16, 19], dtype=int64),
 array([17, 18, 19], dtype=int64),
 array([17, 18, 19], dtype=int64),
 array([ 2,  3, 19], dtype=int64),
 array([11, 18, 19], dtype=int64),
 array([17, 18, 19], dtype=int64)]

In [6]:
#type(x[0])

# np.intersect1d(x)
print(set(arr[0]).intersection(*arr))
print(set(arr[0]).union(*arr))
print(set(arr[0]).difference(*arr))
print(set(arr[0]).difference_update(*arr))


# for i in x:
#     print(i)

{19}
{2, 3, 11, 16, 17, 18, 19}
set()
None


In [7]:
from sklearn.metrics import hamming_loss

hamming_loss(y_test, predictions)

0.23232323232323232